language: cpp
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
sudo: required
os: linux
dist: bionic

matrix:
  include:
    - addons:
        apt:
          sources:
            - sourceline: 'ppa:ricotz/toolchain' #more recent meson version
          packages:
            - clang-8
            - lld-8
            - gcc-multilib
            - g++-multilib
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
        - CLANG_VERSION=8 LINK_TYPE=static
      compiler: clang

    - addons:
        apt:
          sources:
            - sourceline: 'ppa:ricotz/toolchain' #more recent meson version
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - lld-9
            - gcc-multilib
            - g++-multilib
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
        - CLANG_VERSION=9 LINK_TYPE=static CC_VERSION=9
      compiler: clang

    - addons:
        apt:
          sources:
            - sourceline: 'ppa:ricotz/toolchain' #more recent meson version
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - lld-9
            - gcc-multilib
            - g++-multilib
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
        - CLANG_VERSION=9 LINK_TYPE=dynamic CC_VERSION=9
      compiler: clang

    - addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test' # workaround for disallowed source
            - sourceline: 'ppa:ricotz/toolchain' #more recent meson version
          packages:
            - gcc-8
            - g++-8
            - gcc-8-multilib
            - g++-8-multilib
            - python3
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
        - GCC_VERSION=8 LINK_TYPE=static
      compiler: gcc

    - addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test' # workaround for disallowed source
            - sourceline: 'ppa:ricotz/toolchain' #more recent meson version
          packages:
            - gcc-9
            - g++-9
            - gcc-9-multilib
            - g++-9-multilib
            - python3
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
        - GCC_VERSION=9 LINK_TYPE=static CC_VERSION=9
      compiler: gcc

    - addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test' # workaround for disallowed source
            - sourceline: 'ppa:ricotz/toolchain'
          packages:
            - gcc-9
            - g++-9
            - gcc-9-multilib
            - g++-9-multilib
            - python3
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
        - GCC_VERSION=9 LINK_TYPE=dynamic CC_VERSION=9
      compiler: gcc

before_script:
  - export PATH=/usr/bin:$PATH LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/build:$LD_LIBRARY_PATH
  - travis/prepare.sh
script:
  - travis/build.sh

before_deploy:
  - git fetch --unshallow
  - export COMMIT_NUM="$(git rev-list --count HEAD)"
  - export COMMIT_SHORT_SHA="$(git rev-parse --short HEAD)"
  - travis/package.sh
deploy:
  - provider: releases
    api_key:
      secure: uGexzy3F5r3zVR/8lAOHVnwIhQ2VsV0Dx2sZgztmmK4YGWt1th5FH8iOWRc5LK8liufiz9pmfQov4TsCYTFFsi3j5zBdkWc0J+VoBWmy81Ua/CfKKaDQd/ynzaQ9w1+11/5sBciXEf3mekbTs2PNnoewwBIKLGcHHCrMSy6LexIpKh5IzXarwt1YUpVQsMpoEJ+wi8TNrN7d0hNO0uV/l6yPyEJ5vSmfEiq1mdKr/GlleBwSNncY2bV6hfoSedis+PO39mTDqQF4i3tGXPhtl0Ky6byUTzVXogpvQt05g9DMqM567U+Q1UJJuOdM1EN9cJDgufLifUQojFAdt8OH34thydKL2+WI4DTwpHw3yr4mVzHPyqWX+Pk3u19QTYTOtePKpkDE7OuHIstv9u0IXDKB7aYkuz2sO4ThrKV4TEBEW4GWVs8BuIaW43fh6NROMW1X+6Q8azZG5ab63dN7zvUkbgsuEDlAkIfMtVO0QqdSvEfE9HZSFSJlzenmZ4O/MM48PTbMAJBKdqruRiH5VB8Y5qwri7oUaxZ9cfTIB6rveAFKQcOXfhjTZXxiMOOoTROloZaQQJW7CEb44OurJpdkUr/RO23/+hWNlA3cJ3pyDQLON2JEerFschFxw3X5YLiwBMuNzBYYa5p6zqFdul4jEBRWh4qnFZvf5sU/Rxk=
    file: upload/spmod-$TRAVIS_OS_NAME-$TRAVIS_TAG-$CC$CC_VERSION-$LINK_TYPE.tar.xz
    skip_cleanup: true
    draft: true
    tag_name: $TRAVIS_TAG
    on:
      tags: true
      branch: /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      condition: $CLANG_VERSION = 9 || $GCC_VERSION = 9
  - provider: s3
    local-dir: upload/s3
    access_key_id: 
      secure: g5eMcCQxblr3kXOtnGeAn/HWVLlRilOjU2+DsO/q0pcnkE6mqRQvXRhWt+fHV1YqBXV1JCdzTlGqv48Mt1X0LQMQYn+Gf1WomutQOcdrT9myWXqLLiXTNqqfoq+yBYLbtHDzwzamYu9iAKD5QY8XwcR2k3r4ThrVq/8wkIkU6HVRwhc4FV/oETtSe0E1SyYsMDmJqLg72TXmZdujmiCp34qjQKxOMFxMykoj9O2FcDmv0CMzOjZap8p9H2ove3U+mI+VUeQ9r1eo72tLtLS6ossH94MI9oBJ8NnONo1nnkskL4/GGqEqGnjcuvH3dSQHhpjqLoDOdJKodWFbPBvsjkpOeSmJmhl3rljMM6Jz0s65gkv8ilNVoGUIahvso+vMV3SMKsqjlCBacIBimar9q6BIouXIioHgnafbKJeqFP/aX7TD1mGJl7j3BFKHKXuBln0etlHfvFy7DR00SRBG8DGjRVKEJTwNc75ma5DQuTbSkf+8Tn12mQA+Ei8GGt68J2/ZERjERlszcphPm+E6X+x8x5wPIwJG58kuxzMGnglaV81LceX8gAkRo4pmM5jkIOjXjPRXw77b0DA9ZSQCzGL2LNi0IDk6kN8Z6VRnaflTFGHcbE0d5vGK0jrFls2IJ/EmCfnt1GRV0+10w9/HP+x642Ud4uXWskzE/QhcuKY=
    secret_access_key:
      secure: sJ7abLWZlcHHBlIjJqJ/w+skr2JqQ7qmuUG8MP3JCxRZCm3YF4n2AXuJGslTMmmyslYhzvO2pDUv/EE6rZoxPCoMTDd+12hG1KgUHec5cJKOd5wxdRL8qmBvGHK26Y4xCqEAL4HfX+NPCIUMSDKhekdux+hiMloJeSB/w4vafR13JADm5kVRgqEA0z1P1qOvK90ZtEFHYDYD0uXzWHtqHJa9Z3VkYjaVF6Nsaq3ElwJqedXskPm4ktwg7J3AXKemmiEti2q8AggvQ1IpvLkr+OhCTBHOurW48R7x/ewpjZz7nRBMEYQU91WPHMD2UAJStiggfZ1CKQyrdxbpd7SdODiJkqfno2UYK2nVmTi2MvjdCxssOZs8X+2iLseIBvIg+X8Hw8/hhsU1ntoNd7EuyInFd4afZjLQ/L7Ey4ai0e02GkW8M+SqQ2urU35Hsfcn5thXWOAH+1MSc96snLAq3RWOa/aW58np+1DDrKa0QFVyhzYXvnQcI5DEIiC+n4emSL2nenjS0zeWCG52IuPHrxBCIjbV29fRrrzWeznLHiqus36IABF5rEfZKPR3RRpYF2Oz8nkvB3IRTxyTH1cDVDxWQg77O4P/9anB1KcP0Tfx4aIzOTaEmGX4dWZq7CeE/TiriqZu1VzIrQNHGVuifAfC1FucrCyq7siAIFrKbDs=
    bucket: spmod
    region: eu-central-1
    skip_cleanup: true
    on:
      branch: master
      condition: $CLANG_VERSION = 9 || $GCC_VERSION = 9
